sudo: false
language: python
install: pip install tox
matrix:
  include:
  - python: "2.6"
  - python: "2.7"
  - python: "3.6"
script: tox -e $TOX_ENV
after_success:
- test $TOX_ENV = docs && scripts/push-docs
